workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      groups:
        - whisprmobile
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter upgrade
          flutter pub get
      
      - name: Build Android Release
        script: |
          flutter build apk --release
          flutter build appbundle --release
      
      - name: Publish to GitHub
        script: |
          #!/bin/bash
          
          # Make script executable
          chmod +x ./scripts/create-github-release.sh
          
          # Run the GitHub release script
          ./scripts/create-github-release.sh
    artifacts:
      - build/android/app/outputs/apk/release/*.apk
      - build/android/app/outputs/bundle/release/*.aab
    publishing:
      email:
        recipients:
          - techtune.it.solutions@gmail.com
        notify:
          success: true
          failure: true
