-- Seed non-AI powered games (poem next line, blog next line, guess next line)
-- These games use pre-built content without AI generation
-- Games can be resumed where left off via chronicles_game_sessions
-- Following the same pattern as 055-non-ai-games-seed.sql

-- Insert non-AI games
insert into public.chronicles_games (slug, title, description, game_type, audience, difficulty, is_offline_ready, is_ai_powered, is_published, config)
values
  ('poem_next_line_romance', 'Romantic Poetry Flow', 'Continue romantic poems line by line. Master poetic expression of love, longing, and emotion.', 'poem_next_line', 'all', 'beginner', true, false, true, jsonb_build_object(
    'topic', 'romantic poetry',
    'instruction', 'Choose the best line to continue the romantic poem based on tone, rhythm, and emotional imagery.',
    'total_challenges', 10,
    'can_resume', true
  )),
  ('poem_next_line_nature', 'Nature Poetry Journey', 'Explore nature through poetry. Continue verses about landscapes, seasons, and the natural world.', 'poem_next_line', 'all', 'beginner', true, false, true, jsonb_build_object(
    'topic', 'nature poetry',
    'instruction', 'Select the line that best continues the nature poem, maintaining imagery and flow.',
    'total_challenges', 10,
    'can_resume', true
  )),
  ('blog_next_line_lifestyle', 'Lifestyle Blog Builder', 'Build engaging lifestyle blog posts paragraph by paragraph.', 'blog_next_line', 'all', 'beginner', true, false, true, jsonb_build_object(
    'topic', 'lifestyle blogging',
    'instruction', 'Choose the best continuation for the lifestyle blog post based on clarity and value.',
    'total_challenges', 10,
    'can_resume', true
  )),
  ('blog_next_line_tech', 'Tech Blog Builder', 'Build technology blog posts with clear explanations and practical insights.', 'blog_next_line', 'all', 'intermediate', true, false, true, jsonb_build_object(
    'topic', 'tech blogging',
    'instruction', 'Choose the continuation that explains technical concepts clearly and engagingly.',
    'total_challenges', 10,
    'can_resume', true
  )),
  ('guess_next_line_mystery', 'Mystery Line Guessing', 'Guess the best next line in mystery and suspense passages.', 'guess_next_line', 'all', 'intermediate', true, false, true, jsonb_build_object(
    'topic', 'mystery writing',
    'instruction', 'Select the line that best continues the mystery passage, maintaining suspense and tone.',
    'total_challenges', 10,
    'can_resume', true
  )),
  ('guess_next_line_fantasy', 'Fantasy Line Guessing', 'Continue fantasy passages with imaginative and world-building lines.', 'guess_next_line', 'all', 'beginner', true, false, true, jsonb_build_object(
    'topic', 'fantasy writing',
    'instruction', 'Choose the line that best continues the fantasy passage in tone and world-building.',
    'total_challenges', 10,
    'can_resume', true
  ))
on conflict (slug) do update set
  title = excluded.title,
  description = excluded.description,
  game_type = excluded.game_type,
  audience = excluded.audience,
  difficulty = excluded.difficulty,
  is_offline_ready = excluded.is_offline_ready,
  is_ai_powered = excluded.is_ai_powered,
  is_published = excluded.is_published,
  config = excluded.config,
  updated_at = now();

-- Seed challenges for Romantic Poetry Flow
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which line best continues this romantic poem?', 'Your eyes are oceans I could sail forever, deep and endless and full of stars.',
     jsonb_build_array('I see nothing but darkness there.', 'My heart is a ship lost in your beauty.', 'The ocean is cold and dangerous.'),
     'My heart is a ship lost in your beauty.',
     'This extends the ocean metaphor, creating a cohesive romantic image.',
     'Romantic poetry maintains consistent metaphors throughout.',
     'beginner'),
    (2, 'Choose the best romantic continuation:', 'Love is not a fleeting moment but a fire that burns eternal and steady.',
     jsonb_build_array('Love disappears like morning mist.', 'It warms the soul through every changing season.', 'Fire burns everything to ashes.'),
     'It warms the soul through every changing season.',
     'This continues the fire metaphor while emphasizing love''s enduring nature.',
     'Metaphors in love poetry should emphasize positive enduring qualities.',
     'beginner'),
    (3, 'Which line flows best?', 'Your voice is music I would listen to for all eternity, never tiring of its melody.',
     jsonb_build_array('Music is loud and annoying sometimes.', 'Each word is a note that plays upon my heart.', 'I prefer silence over any music.'),
     'Each word is a note that plays upon my heart.',
     'This extends the music metaphor to an emotional, heartfelt level.',
     'Sensory metaphors create deeper emotional connections in poetry.',
     'beginner'),
    (4, 'Select the best poetic continuation:', 'The first time I saw you, time itself paused, taking a breath before continuing.',
     jsonb_build_array('Time is just an illusion anyway.', 'In that suspended moment, I found my forever.', 'I forgot what you looked like.'),
     'In that suspended moment, I found my forever.',
     'This captures the timelessness of love and the significance of that first meeting.',
     'Love poetry often plays with the concept of time.',
     'beginner'),
    (5, 'Choose the line that maintains the mood:', 'Your touch is gentler than the morning dew, soft and full of promise for the day ahead.',
     jsonb_build_array('The morning dew is wet and inconvenient.', 'You hold my hand and suddenly I believe in everything.', 'Dew disappears when the sun comes out.'),
     'You hold my hand and suddenly I believe in everything.',
     'This transforms the gentle imagery into a feeling of hope and belief.',
     'Romantic poetry moves from physical sensation to emotional meaning.',
     'intermediate'),
    (6, 'Which line best continues this romantic image?', 'I would cross deserts, climb mountains, and swim oceans just to see you smile.',
     jsonb_build_array('Smiling is overrated anyway.', 'Your smile is worth every step of that impossible journey.', 'Deserts are too hot and dangerous.'),
     'Your smile is worth every step of that impossible journey.',
     'This validates the grand gesture with the simple reward of love.',
     'Contrast between grand imagery and simple emotion creates powerful poetry.',
     'beginner'),
    (7, 'Select the most romantic continuation:', 'In a world of chaos and noise, your heartbeat is my favorite melody.',
     jsonb_build_array('Heartbeats are just medical functions.', 'It guides me home when I am lost in the crowd.', 'I prefer silence to heartbeats.'),
     'It guides me home when I am lost in the crowd.',
     'This reframes love as an anchor and a compass in a chaotic world.',
     'Love poetry creates intimacy by contrasting external chaos with internal peace.',
     'intermediate'),
    (8, 'Choose the line that best fits:', 'You are the poem I will never finish writing, each day a new stanza waiting to be composed.',
     jsonb_build_array('I hate writing poems.', 'Our love story unfolds with every sunrise.', 'Poems are better when they are short.'),
     'Our love story unfolds with every sunrise.',
     'This extends the poem metaphor to the daily renewal of love.',
     'Metaphors that suggest continuous growth reflect mature love.',
     'intermediate'),
    (9, 'Which line continues the poetic flow?', 'Hold my hand beneath the stars, and let us write our names across the sky.',
     jsonb_build_array('The stars will eventually burn out.', 'Our love will outshine even the brightest constellation.', 'Writing in the sky is impossible.'),
     'Our love will outshine even the brightest constellation.',
     'This elevates the romantic gesture to a cosmic scale.',
     'Love poetry often uses cosmic imagery to express eternal devotion.',
     'beginner'),
    (10, 'Select the best continuation:', 'I loved you before we met, in every dream I never knew I had.',
     jsonb_build_array('Dreams are not real.', 'You are the memory I was waiting to make.', 'I never dream about anything.'),
     'You are the memory I was waiting to make.',
     'This beautifully suggests that true love feels destined and predestined.',
     'The concept of destined love is a powerful theme in romantic poetry.',
     'intermediate')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'poem_next_line_romance'
on conflict do nothing;

-- Seed challenges for Nature Poetry Journey
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which line best continues this nature poem?', 'The morning sun kissed the dewdrops, awakening the slumbering meadow.',
     jsonb_build_array('The meadow was dead and brown.', 'Flowers stretched their petals toward the golden light.', 'Night fell quickly upon the land.'),
     'Flowers stretched their petals toward the golden light.',
     'This maintains the personification and the awakening theme.',
     'Personification brings nature poetry to life.',
     'beginner'),
    (2, 'Choose the best continuation:', 'The river whispered ancient secrets as it wound through the ancient forest.',
     jsonb_build_array('The river was polluted and dirty.', 'Trees leaned closer to hear its timeless tales.', 'The forest had no secrets at all.'),
     'Trees leaned closer to hear its timeless tales.',
     'This extends the personification, making the entire scene interactive.',
     'Consistent personification creates a living, breathing natural world.',
     'beginner'),
    (3, 'Which line flows best?', 'Autumn painted the leaves in fiery hues before letting them dance to the ground.',
     jsonb_build_array('The leaves were all green and boring.', 'Each falling leaf wrote a goodbye note on the earth.', 'Leaves should stay on trees forever.'),
     'Each falling leaf wrote a goodbye note on the earth.',
     'This gives the falling leaves meaning and beauty in their descent.',
     'Transitions in nature are opportunities for poetic reflection.',
     'beginner'),
    (4, 'Select the best nature continuation:', 'The owl called across the silent valley, its voice echoing through the mountain pass.',
     jsonb_build_array('Owls are not very important birds.', 'The moon listened in silver silence.', 'The valley was loud with traffic.'),
     'The moon listened in silver silence.',
     'This creates a majestic night scene with the moon as witness.',
     'Nature poetry often creates relationships between different natural elements.',
     'beginner'),
    (5, 'Choose the line that maintains the imagery:', 'Snow fell softly through the winter air, each flake a tiny piece of quiet.',
     jsonb_build_array('Snow is cold and unpleasant.', 'The world wrapped itself in a blanket of stillness.', 'Snow melted before it touched the ground.'),
     'The world wrapped itself in a blanket of stillness.',
     'This extends the imagery from the snowflakes to the entire scene.',
     'Imagery should expand from the specific to the general.',
     'intermediate'),
    (6, 'Which line best continues?', 'The thunder rolled across the plains, a drumbeat for the dancing rain.',
     jsonb_build_array('Thunder is loud and scary.', 'Lightning wrote poetry across the darkened sky.', 'The rain stopped immediately.'),
     'Lightning wrote poetry across the darkened sky.',
     'This adds another element to the storm symphony with poetic flair.',
     'Storm imagery can be portrayed as a dramatic performance.',
     'intermediate'),
    (7, 'Select the most appropriate continuation:', 'The ocean waves composed a lullaby, gentle rhythms on the sandy shore.',
     jsonb_build_array('The ocean is full of dangerous creatures.', 'The seagulls joined in with their morning chorus.', 'I prefer the mountains to the ocean.'),
     'The seagulls joined in with their morning chorus.',
     'This adds harmony and layers to the natural symphony.',
     'Nature''s sounds can be portrayed as a musical composition.',
     'intermediate'),
    (8, 'Choose the line that fits the style:', 'The desert stretched endlessly, a sea of sand beneath the blazing sun.',
     jsonb_build_array('Deserts are boring and empty.', 'Each dune held stories of ancient winds and travelers.', 'I would rather be at the beach.'),
     'Each dune held stories of ancient winds and travelers.',
     'This gives the vast desert depth and history.',
     'Even barren landscapes can be rich with poetic meaning.',
     'beginner'),
    (9, 'Which sentence continues effectively?', 'The butterfly emerged from its cocoon, wings still damp with transformation.',
     jsonb_build_array('Butterflies are just insects.', 'It rested in the morning sun, learning to fly.', 'The cocoon was empty now.'),
     'It rested in the morning sun, learning to fly.',
     'This captures the tender moment of new life and beginning.',
     'Transformation in nature symbolizes hope and renewal.',
     'beginner'),
    (10, 'Select the best continuation:', 'The mountain peaks touched the clouds, guardians of the valley below.',
     jsonb_build_array('Mountains are just rocks.', 'They had watched centuries pass in patient silence.', 'The valley was low and unimportant.'),
     'They had watched centuries pass in patient silence.',
     'This personifies the mountains as ancient, wise witnesses.',
     'Timeless imagery gives nature poetry a sense of scale and wonder.',
     'intermediate')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'poem_next_line_nature'
on conflict do nothing;

-- Seed challenges for Lifestyle Blog Builder
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which sentence best continues this lifestyle blog?', 'Morning routines set the tone for a productive day. How we start our mornings matters.',
     jsonb_build_array('Mornings are the worst part of the day.', 'Simple habits like gratitude and movement can transform your mornings.', 'You should sleep through the morning.'),
     'Simple habits like gratitude and movement can transform your mornings.',
     'This provides actionable advice that improves the reader''s life.',
     'Lifestyle blogs should offer practical, positive suggestions.',
     'beginner'),
    (2, 'Choose the best continuation:', 'Minimalism is not about owning nothing, but about making room for what truly matters.',
     jsonb_build_array('Minimalism means getting rid of everything.', 'It creates space for experiences, relationships, and peace of mind.', 'Owning stuff is the key to happiness.'),
     'It creates space for experiences, relationships, and peace of mind.',
     'This reframes minimalism as abundance of meaning, not scarcity of things.',
     'Lifestyle content should reframe concepts positively.',
     'beginner'),
    (3, 'Which sentence flows best?', 'Self-care has become a buzzword, but its essence is simple: treating yourself with kindness.',
     jsonb_build_array('Self-care is selfish and unnecessary.', 'It means listening to your body and honoring your needs.', 'Self-care only means taking baths.'),
     'It means listening to your body and honoring your needs.',
     'This demystifies self-care and makes it accessible.',
     'Simplify complex topics into relatable, actionable ideas.',
     'beginner'),
    (4, 'Select the best blog continuation:', 'Building healthy relationships requires communication, patience, and mutual respect.',
     jsonb_build_array('Relationships are too much work.', 'It begins with understanding that we all have different love languages.', 'You should avoid relationships entirely.'),
     'It begins with understanding that we all have different love languages.',
     'This provides a specific framework for improving relationships.',
     'General advice becomes powerful when connected to a specific concept.',
     'beginner'),
    (5, 'Choose the line that maintains blog voice:', 'Travel broadens perspectives in ways that books and screens cannot replicate.',
     jsonb_build_array('Travel is a waste of money.', 'Stepping into another culture teaches you about the world and yourself.', 'You can learn everything from the internet.'),
     'Stepping into another culture teaches you about the world and yourself.',
     'This captures the dual benefit of travel: external discovery and internal growth.',
     'Lifestyle content connects external activities to internal growth.',
     'intermediate'),
    (6, 'Which line best continues?', 'Decluttering your space can declutter your mind. The connection between environment and mental clarity is powerful.',
     jsonb_build_array('Clutter does not affect your mind at all.', 'A tidy space allows focus and creativity to flow more freely.', 'You should embrace the clutter.'),
     'A tidy space allows focus and creativity to flow more freely.',
     'This validates the premise with a clear benefit.',
     'Connect practical actions to mental and emotional benefits.',
     'beginner'),
    (7, 'Select the most appropriate continuation:', 'Digital minimalism is about intentional technology use, not complete avoidance.',
     jsonb_build_array('Technology is evil and should be banned.', 'It means choosing apps and tools that add value to your life.', 'You should never use technology again.'),
     'It means choosing apps and tools that add value to your life.',
     'This provides a balanced, practical approach to technology.',
     'Lifestyle advice should be balanced, not extreme.',
     'intermediate'),
    (8, 'Choose the line that fits the style:', 'Meal prepping on Sundays can save hours during a busy week.',
     jsonb_build_array('Meal prepping is not worth the effort.', 'A few hours of planning leads to healthier, stress-free meals.', 'You should eat out every single meal.'),
     'A few hours of planning leads to healthier, stress-free meals.',
     'This frames the effort as an investment with clear returns.',
     'Show the payoff for the effort you''re asking readers to invest.',
     'beginner'),
    (9, 'Which sentence continues effectively?', 'Journaling is a powerful tool for self-discovery and emotional processing.',
     jsonb_build_array('Journaling is a waste of paper.', 'Putting thoughts to paper helps untangle the knots in our minds.', 'You should keep everything bottled up inside.'),
     'Putting thoughts to paper helps untangle the knots in our minds.',
     'This uses a vivid metaphor to explain the benefit of journaling.',
     'Metaphors make abstract benefits concrete and memorable.',
     'beginner'),
    (10, 'Select the best continuation:', 'Mindful eating is not a diet but a practice of being present with your food.',
     jsonb_build_array('Diets are the only way to be healthy.', 'It helps you enjoy meals more and make healthier choices naturally.', 'Mindful eating takes too much time and effort.'),
     'It helps you enjoy meals more and make healthier choices naturally.',
     'This presents mindful eating as an enhancement, not a restriction.',
     'Frame lifestyle changes as additions, not restrictions.',
     'intermediate')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'blog_next_line_lifestyle'
on conflict do nothing;

-- Seed challenges for Tech Blog Builder
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which sentence best continues this tech blog?', 'Artificial intelligence is transforming how we work, but understanding it is simpler than you think.',
     jsonb_build_array('AI is too complex for anyone to understand.', 'At its core, AI recognizes patterns and makes predictions based on data.', 'You should avoid AI technology entirely.'),
     'At its core, AI recognizes patterns and makes predictions based on data.',
     'This demystifies AI with a clear, simple explanation.',
     'Tech blogs should make complex concepts accessible.',
     'beginner'),
    (2, 'Choose the best continuation:', 'Cloud computing has revolutionized how businesses store and access data.',
     jsonb_build_array('Cloud computing is just a fad that will pass.', 'Instead of physical servers, companies use remote data centers accessible from anywhere.', 'Storing data in the cloud is dangerous.'),
     'Instead of physical servers, companies use remote data centers accessible from anywhere.',
     'This explains the core concept of cloud computing clearly.',
     'Define technical terms in simple, relatable language.',
     'intermediate'),
    (3, 'Which sentence flows best?', 'Cybersecurity is everyone''s responsibility, not just the IT department''s.',
     jsonb_build_array('Only IT people need to worry about security.', 'Simple practices like strong passwords and awareness can prevent most threats.', 'Cybersecurity is impossible to maintain.'),
     'Simple practices like strong passwords and awareness can prevent most threats.',
     'This empowers readers by showing them they can make a difference.',
     'Tech advice should empower, not intimidate.',
     'beginner'),
    (4, 'Select the best blog continuation:', 'Open source software powers most of the internet you use every day.',
     jsonb_build_array('Open source software is unreliable.', 'From Linux servers to WordPress sites, collaborative code runs the web.', 'Only paid software is worth using.'),
     'From Linux servers to WordPress sites, collaborative code runs the web.',
     'This provides concrete examples that readers may recognize.',
     'Use familiar examples to explain unfamiliar concepts.',
     'intermediate'),
    (5, 'Choose the line that maintains blog voice:', 'Learning to code is not about memorizing syntax but about learning to think logically.',
     jsonb_build_array('Coding is way too difficult for most people.', 'Problem-solving skills matter more than knowing every programming function.', 'Only geniuses can learn to code.'),
     'Problem-solving skills matter more than knowing every programming function.',
     'This reframes coding as an accessible skill based on logic.',
     'Reduce intimidation by reframing technical skills as thinking skills.',
     'beginner'),
    (6, 'Which line best continues?', 'Version control helps teams collaborate on code without stepping on each other''s work.',
     jsonb_build_array('Version control creates more problems than it solves.', 'It tracks changes, resolves conflicts, and maintains a complete history of your project.', 'Collaborating on code is impossible.'),
     'It tracks changes, resolves conflicts, and maintains a complete history of your project.',
     'This explains the key benefits of version control succinctly.',
     'Explain what a tool does before explaining how to use it.',
     'intermediate'),
    (7, 'Select the most appropriate continuation:', 'Mobile-first design ensures websites work perfectly on devices of all sizes.',
     jsonb_build_array('Only desktop websites matter.', 'Designing for small screens first forces clarity and efficiency in your interface.', 'Mobile design is not important.'),
     'Designing for small screens first forces clarity and efficiency in your interface.',
     'This explains the rationale behind mobile-first methodology.',
     'Explain the "why" behind technical best practices.',
     'intermediate'),
    (8, 'Choose the line that fits the style:', 'APIs are how different software applications talk to each other.',
     jsonb_build_array('APIs are unnecessary for modern development.', 'Think of them as waiters delivering requests between two kitchens.', 'Software should never communicate with other software.'),
     'Think of them as waiters delivering requests between two kitchens.',
     'This uses a restaurant metaphor to make APIs relatable.',
     'Analogies are powerful tools for explaining technical concepts.',
     'beginner'),
    (9, 'Which sentence continues effectively?', 'Debugging is the art of figuring out why code is not doing what you expected.',
     jsonb_build_array('Code always works on the first try.', 'Patience and a systematic approach turn frustrating bugs into learning opportunities.', 'Debugging is a sign of failure.'),
     'Patience and a systematic approach turn frustrating bugs into learning opportunities.',
     'This reframes debugging positively as a learning process.',
     'Tech blogs should normalize challenges and encourage persistence.',
     'beginner'),
    (10, 'Select the best continuation:', 'Database indexing speeds up queries but requires thoughtful planning to implement well.',
     jsonb_build_array('Database indexing always slows things down.', 'Like a book''s index, it helps find information without reading every page.', 'You should never use database indexes.'),
     'Like a book''s index, it helps find information without reading every page.',
     'This uses a simple, universal analogy to explain indexing.',
     'Relate technical concepts to everyday experiences everyone understands.',
     'intermediate')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'blog_next_line_tech'
on conflict do nothing;

-- Seed challenges for Mystery Line Guessing
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which line best continues this mystery passage?', 'The door creaked open, revealing nothing but darkness and the faint smell of old paper.',
     jsonb_build_array('The room was brightly lit and welcoming.', 'She stepped forward, her heart racing with each footstep.', 'She turned around and went home.'),
     'She stepped forward, her heart racing with each footstep.',
     'This builds tension by emphasizing the character''s fear and determination.',
     'Mystery writing uses character reactions to build suspense.',
     'beginner'),
    (2, 'Choose the best continuation:', 'The detective studied the evidence, knowing the answer was hiding in plain sight.',
     jsonb_build_array('The detective gave up on the case.', 'Every detail mattered, even the ones that seemed insignificant.', 'The evidence was all fake and staged.'),
     'Every detail mattered, even the ones that seemed insignificant.',
     'This sets up the mystery convention that small details hold the key.',
     'Mystery stories teach readers to pay attention to details.',
     'beginner'),
    (3, 'Which line flows best?', 'The letter arrived without a return address, postmarked from a town that did not exist.',
     jsonb_build_array('She threw the letter in the trash.', 'Her hands trembled as she unfolded the yellowed paper within.', 'The post office had made a mistake.'),
     'Her hands trembled as she unfolded the yellowed paper within.',
     'This uses physical reaction to show emotional impact and suggests the letter is old.',
     'Physical details reveal emotional states in mystery writing.',
     'beginner'),
    (4, 'Select the best mystery continuation:', 'A single footprint in the dusty attic floor suggested someone had been here recently.',
     jsonb_build_array('The footprint was clearly a dog''s paw.', 'But the door had been locked from the inside for years.', 'Footprints are common in attics.'),
     'But the door had been locked from the inside for years.',
     'This creates a contradiction that deepens the mystery.',
     'Contradictions and impossibilities are the heart of good mysteries.',
     'intermediate'),
    (5, 'Choose the line that maintains the tone:', 'The clock struck midnight as she reached the old mansion, its windows dark and watching.',
     jsonb_build_array('The mansion was bright and cheery inside.', 'Somewhere inside, a light flickered briefly, then vanished.', 'She decided the mansion looked nice.'),
     'Somewhere inside, a light flickered briefly, then vanished.',
     'This hints at presence inside while maintaining the ominous mood.',
     'Hint at danger rather than showing it directly to maintain suspense.',
     'intermediate'),
    (6, 'Which line best continues?', 'The photograph was dated fifty years ago, but the person in it looked exactly like her.',
     jsonb_build_array('Photographs fade over time naturally.', 'She dropped the picture as if burned by its impossible truth.', 'It was probably just someone who looked similar.'),
     'She dropped the picture as if burned by its impossible truth.',
     'This conveys the shock of the discovery through physical reaction.',
     'Reveal the emotional impact of discoveries through action, not description.',
     'beginner'),
    (7, 'Select the most appropriate continuation:', 'Three keys lay on the table, each one rusted and ancient, each one a question without an answer.',
     jsonb_build_array('Keys are just made of metal.', 'Which door did they open, and what would be found behind it?', 'She threw the keys away.'),
     'Which door did they open, and what would be found behind it?',
     'This poses the mystery question directly, engaging the reader.',
     'Good mysteries raise questions that compel readers forward.',
     'intermediate'),
    (8, 'Choose the line that fits the style:', 'The library held more secrets than books, and she intended to find every one.',
     jsonb_build_array('Libraries are boring places.', 'Starting with the locked section in the basement, she began her search.', 'She decided to read a novel instead.'),
     'Starting with the locked section in the basement, she began her search.',
     'This establishes a clear objective and a starting point for investigation.',
     'Mystery protagonists need clear goals and actions.',
     'beginner'),
    (9, 'Which sentence continues effectively?', 'The suspect had an alibi that was too perfect, too detailed to be true.',
     jsonb_build_array('The alibi was probably completely accurate.', 'A perfect alibi is often more suspicious than no alibi at all.', 'All alibis should be trusted immediately.'),
     'A perfect alibi is often more suspicious than no alibi at all.',
     'This introduces the mystery convention of the too-perfect alibi.',
     'Mysteries subvert expectations and question obvious answers.',
     'intermediate'),
    (10, 'Select the best continuation:', 'The final clue was hidden in something she saw every day but never truly noticed.',
     jsonb_build_array('She never found the clue.', 'The answer had been waiting on her own bookshelf all along.', 'Clues are usually obvious from the start.'),
     'The answer had been waiting on her own bookshelf all along.',
     'This creates a satisfying reveal that feels both surprising and inevitable.',
     'The best mysteries hide answers in plain sight.',
     'intermediate')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'guess_next_line_mystery'
on conflict do nothing;

-- Seed challenges for Fantasy Line Guessing
insert into public.chronicles_game_challenges (game_id, challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
select
  g.id,
  t.challenge_order,
  t.question,
  t.context,
  t.options,
  t.correct_answer,
  t.explanation,
  t.teaching_point,
  t.difficulty
from public.chronicles_games g
cross join lateral (
  values
    (1, 'Which line best continues this fantasy passage?', 'The dragon''s scales shimmered like a thousand emeralds in the dying sunlight.',
     jsonb_build_array('Dragons are not real.', 'Its golden eyes watched the intruders with ancient intelligence.', 'The dragon was ordinary and unremarkable.'),
     'Its golden eyes watched the intruders with ancient intelligence.',
     'This gives the dragon personality and wisdom beyond its physical description.',
     'Fantasy creatures should feel real and intelligent, not just magical.',
     'beginner'),
    (2, 'Choose the best continuation:', 'The wizard raised his staff, and the air crackled with centuries of gathered power.',
     jsonb_build_array('Nothing happened at all.', 'Blue light erupted from the crystal, weaving a shield around the village.', 'The staff was just a stick.'),
     'Blue light erupted from the crystal, weaving a shield around the village.',
     'This delivers on the promise of magic while showing its protective purpose.',
     'Magic in fantasy should have clear visual effects and purposes.',
     'beginner'),
    (3, 'Which line flows best?', 'The enchanted forest hummed with a melody only those pure of heart could hear.',
     jsonb_build_array('The forest was completely silent.', 'Ancient trees swayed in rhythm, their leaves singing forgotten songs.', 'The forest had no special qualities.'),
     'Ancient trees swayed in rhythm, their leaves singing forgotten songs.',
     'This brings the enchanted forest to life through musical imagery.',
     'Fantasy settings should feel alive and magical, not just described.',
     'beginner'),
    (4, 'Select the best fantasy continuation:', 'She discovered a hidden realm where time flowed like honey, slow and sweet.',
     jsonb_build_array('Time always flows the same everywhere.', 'Here, centuries passed in hours, yet she aged not a single day.', 'Hidden realms do not exist.'),
     'Here, centuries passed in hours, yet she aged not a single day.',
     'This establishes the unique rules of the fantasy realm.',
     'Fantasy worlds need their own internal logic and rules.',
     'intermediate'),
    (5, 'Choose the line that maintains the tone:', 'The prophecy spoke of a child born under the blood moon, destined to unite the divided kingdoms.',
     jsonb_build_array('Prophecies are never accurate.', 'But prophecies are tricky, and fate has a way of surprising even the wisest.', 'The child was born on a Tuesday.'),
     'But prophecies are tricky, and fate has a way of surprising even the wisest.',
     'This adds complexity and foreshadowing to the prophecy trope.',
     'Fantasy prophecies should feel mysterious and open to interpretation.',
     'intermediate'),
    (6, 'Which line best continues?', 'The sword had been waiting for a thousand years, buried in the stone of the ancient temple.',
     jsonb_build_array('The sword was rusty and worthless.', 'When her hand closed around the hilt, the temple itself seemed to breathe.', 'The sword was just a legend.'),
     'When her hand closed around the hilt, the temple itself seemed to breathe.',
     'This makes the sword''s awakening feel momentous and alive.',
     'Legendary objects should feel significant when discovered.',
     'beginner'),
    (7, 'Select the most appropriate continuation:', 'The map showed lands that no living soul had ever visited, marked with warnings in an unknown script.',
     jsonb_build_array('The map was clearly a fake.', 'But every great journey begins with a map that promises more than it reveals.', 'She decided to stay home instead.'),
     'But every great journey begins with a map that promises more than it reveals.',
     'This sets up the adventure while acknowledging the danger.',
     'Fantasy adventures balance danger with the call to adventure.',
     'beginner'),
    (8, 'Choose the line that fits the style:', 'The phoenix rose from the ashes, its feathers aflame with rebirth and renewal.',
     jsonb_build_array('Phoenixes are just mythical birds.', 'It sang a song of endings and beginnings, of circles completing themselves.', 'The phoenix died again immediately.'),
     'It sang a song of endings and beginnings, of circles completing themselves.',
     'This captures the philosophical meaning of the phoenix myth.',
     'Fantasy creatures often carry symbolic meaning beyond their appearance.',
     'intermediate'),
    (9, 'Which sentence continues effectively?', 'The ancient library contained books that wrote themselves, recording events before they happened.',
     jsonb_build_array('Libraries do not work that way.', 'She opened a page and read about her own arrival, written hours before she came.', 'Books cannot write themselves.'),
     'She opened a page and read about her own arrival, written hours before she came.',
     'This demonstrates the magical property through a concrete example.',
     'Show magic through its effects, not just by stating it exists.',
     'beginner'),
    (10, 'Select the best continuation:', 'The gates of the lost city stood before them, carved with stories of a civilization that rivaled the gods.',
     jsonb_build_array('The gates were plain and boring.', 'Beyond them lay answers to questions they had not yet thought to ask.', 'The city was not worth exploring.'),
     'Beyond them lay answers to questions they had not yet thought to ask.',
     'This creates anticipation for discovery and knowledge.',
     'Fantasy discoveries should promise knowledge and wonder, not just treasure.',
     'beginner')
) as t(challenge_order, question, context, options, correct_answer, explanation, teaching_point, difficulty)
where g.slug = 'guess_next_line_fantasy'
on conflict do nothing;